[package]
name = "day13"
version = "0.1.0"
authors = ["dom <wagnr@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
itertools = "0.8"
indoc = "1.0"
